---
all:
    hosts:
        raspi1:
        raspi2:
        raspi3:
        raspi4:
    children:
        master:
            hosts:
                raspi1:
        slave:
            hosts:
                raspi2:
                raspi3:
                raspi4:
