---
# ansible-playbook -i hosts.yml playbook-installpubkeys.yml
- hosts: all
  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa_new.pub') }}"
