---
# ansible-playbook -i hosts.yml playbook.yml
- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io

    - name: Copy conf file
      copy:
        src: etc_docker_daemon.json
        dest: /etc/docker/daemon.json
        backup: yes

    - name: Set /boot/firmware/cmdline.txt up
      copy:
        src: boot_firmware_cmdline.txt
        dest: /boot/firmware/cmdline.txt
      register: cmdline

    - name: Reboot if needed
      reboot:
      when: cmdline.changed
    
    - name: Enable net.bridge.bridge-nf-call-iptables and -iptables6 / copy k8s.conf to sysctl.d
      copy:
        src: etc_sysctl.d_k8s.conf
        dest: /etc/sysctl.d/k8s.conf

    - name: Enable net.bridge.bridge-nf-call-iptables and -iptables6 / reload sysctl settings
      command: sysctl --system

    - name: Enable Docker service
      command: systemctl enable docker.service
    - name: Ensure Docker service is enabled
      service:
        name: docker
        state: started